# Generated by Django 6.0.3 on 2026-03-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cuisines', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('picture', models.ImageField(upload_to='restaurant_pictures/')),
            ],
        ),
    ]
