# Generated by Django 6.0.3 on 2026-03-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisines',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.URLField(default='https://scarborough.originalshawarma.ca/wp-content/uploads/2024/07/placeholder-restaurant.png'),
        ),
    ]
